### ISSUE TITLE
Não roda o `server dev` só seguindo o readme

### ISSUE THREAD

**Issue by cadu-leite** [pyjamasconf/pyjamas.live#3]
tentei rodar e ... 

estou lendo a doc do ZOLA, mas de qualquer modo, segui o readme. tem algo faltando. ;) 

```bash

    $./zola serve
    Building site...
    Error: No `theme.toml` file found. Is the `theme` defined in your `config.toml present in the 
    `themes` directory and does it have a `theme.toml` inside?
     Reason: No such file or directory (os error 2)
```

**Comment by jfunez** [comment]
@cadu-leite o @fabricio-aguiar atualizou o readme com a instrução para inicializar o git submodule que contem o theme. 
tenta isso aqui, para ver se resolve:
https://github.com/pyjamasconf/pyjamas.live/pull/2/files#diff-04c6e90faac2675aa89e2176d2eec7d8R5-R10

**Comment by rochacbruno** [comment]
```
git submodule init
git submodule update
```
