### ISSUE TITLE
Change all appearances of GDG logo to our logo

### ISSUE THREAD

**Issue by camilamaia** [pyjamasconf/pyjamas.live#30]
https://github.com/pyjamasconf/pyjamas.live/blob/a70ff74c7fa1fb7c628200a8e2bf12f1f1451297/static/img/pyjamas.png
https://github.com/pyjamasconf/pyjamas.live/blob/a70ff74c7fa1fb7c628200a8e2bf12f1f1451297/static/img/pyjamas_medium.png
https://github.com/pyjamasconf/pyjamas.live/blob/a70ff74c7fa1fb7c628200a8e2bf12f1f1451297/static/img/pyjamas_small.png
https://github.com/pyjamasconf/pyjamas.live/blob/a70ff74c7fa1fb7c628200a8e2bf12f1f1451297/static/img/logo.png

**Comment by alexandrebarbaruiva** [comment]
Working on it!

**Comment by alexandrebarbaruiva** [comment]
Do we have the logo as `.svg` and `.ico` as well?

**Comment by camilamaia** [comment]
@alexandrebarbaruiva it is black and white: https://drive.google.com/file/d/162616CXMIZ2kHOvNSn8iQJomXFRVsTg2/view?usp=sharing

**Comment by camilamaia** [comment]
> Do we have the logo as `.svg` and `.ico` as well?

Here: https://drive.google.com/drive/u/1/folders/1wZDL10Ls7VZ7C3y8bnhX_NJu8NHOXk0k

I asked in the old pyjamas group and they have it 😊

**Comment by Cheukting** [comment]
Done!
