### ISSUE TITLE
Change Google Loading Animation

### ISSUE THREAD

**Issue by camilamaia** [pyjamasconf/pyjamas.live#34]
When a page is loading, there is this google's animation:

![image](https://user-images.githubusercontent.com/2728804/87226095-f785a480-c367-11ea-9059-816010e04d95.png)

we need to change it to something that matches our design

**Comment by Cheukting** [comment]
We just need to disable it.

**Comment by Cheukting** [comment]
I have disabled it.Maybe we want to:
1) clean it up completely
2) replace it with something else
