### ISSUE TITLE
Update navigation bar

### ISSUE THREAD

**Issue by camilamaia** [pyjamasconf/pyjamas.live#37]
Remove navigation bar links and their respective pages:
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Hackathon"}

https://github.com/pyjamasconf/pyjamas.live/blob/master/_config.yml#L44

**Comment by Cheukting** [comment]
see #42

**Comment by Cheukting** [comment]
Consider it done (for now)
