### ISSUE TITLE
The main page color is too light

### ISSUE THREAD

**Issue by Cheukting** [pyjamasconf/pyjamas.live#49]
Now the words "Pyjamas Conf 2020 December 4th, 2020" is too light and difficult to see against the background.

**Comment by camilamaia** [comment]
One solution would be to change the direction of the gradient and see if it gets better

**Comment by Cheukting** [comment]
Or we can change the color of the fonts?

**Comment by camilamaia** [comment]
Yes, it would be another solution too We need to check which one goes better

**Comment by camilamaia** [comment]
Some ideas...

1. ![Screen Shot 2020-07-13 at 15 50 51](https://user-images.githubusercontent.com/2728804/87342421-9b668000-c521-11ea-9cca-54fe06d3b289.png)

2. ![Screen Shot 2020-07-13 at 15 51 39](https://user-images.githubusercontent.com/2728804/87342432-9f929d80-c521-11ea-9d67-c84b9244d820.png)

3. ![Screen Shot 2020-07-13 at 15 52 18](https://user-images.githubusercontent.com/2728804/87342434-a0c3ca80-c521-11ea-9d3f-4155cd12f6b6.png)

4. ![Screen Shot 2020-07-13 at 15 55 54](https://user-images.githubusercontent.com/2728804/87342438-a15c6100-c521-11ea-85bd-74a7804ac68e.png)

5. ![Screen Shot 2020-07-13 at 15 56 57](https://user-images.githubusercontent.com/2728804/87342444-a28d8e00-c521-11ea-844c-e6c57ab9cee2.png)

I don't know, sorry, I suck as designer 🤷‍♀️ If you have any image you prefer, I can add it too.

**Comment by Cheukting** [comment]
Thank @camilamaia I would prefer #4, I think that it will work best across all screen resolutions

**Comment by camilamaia** [comment]
@Cheukting 4 it is https://github.com/pyjamasconf/pyjamas.live/pull/52 🚀
