### ISSUE TITLE
Adding a page to look for sponsors

### ISSUE THREAD

**Issue by Cheukting** [pyjamasconf/pyjamas.live#66]
We need a page for calling for sponsors. As we are 100% money free, we can ask for sponsors to provide free service or help us to buy stuff. In return, they can have logos on our website and small video advertisement (details TBC) during the conference.

**Comment by Cheukting** [comment]
@itaywss we can discuss what we shall include in this page here.

**Comment by itaywss** [comment]
I sent papercall an email and I'm still waiting for a reply.
Any other service providers we should contact other than streamyard?

**Comment by Cheukting** [comment]
We may have more in the future. Also, other companies who are interested to help us can help us buy stuff. We should have a page to explain that and also detailed what we can offer in return
